# permissions for end users to view flinksqljobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flink-sql-operator
    app.kubernetes.io/managed-by: kustomize
  name: flinksqljob-viewer-role
rules:
- apiGroups:
  - flink.amstee.com
  resources:
  - flinksqljobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flink.amstee.com
  resources:
  - flinksqljobs/status
  verbs:
  - get
